site_name: PhyMath
site_author: 'k.y'

site_url: https://github.com/beidongjiedeguang/phymath
repo_url: https://github.com/beidongjiedeguang/phymath

repo_name: PhyMath

nav:
    - Home: 'index.md'
    - Linear Algebra: 'LinearAlgebra.md'
    - Vectorized Integral: 'Vectorized-integral.md'
    - Guide: 
      - getting-started: 'guide/getting-started.md'
      - getting-style: 'guide/getting-started.md'
    - About: LICENSE.md

plugins:
    - search
    - markdownextradata: {} # https://github.com/rosscdh/mkdocs-markdownextradata-plugin

extra:
  customer:                 # https://github.com/rosscdh/mkdocs-markdownextradata-plugin
    name: Your name here
    web: www.example.com
    salt: salt.example.com
 
markdown_extensions:
    - extra
    - mdx_math 
    - tables
    - fenced_code
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "_"

extra_javascript: 
    - mathjaxhelper.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML

theme: 
    name: readthedocs # mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - yaml
        - python